version: '3.3'
services:
  postgres:
    container_name: pgsql_PRO
    image: postgres:9.3
    restart: always
    environment:
    - POSTGRES_DB=BD_Budget
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=123456789
    volumes:
    - ./bdd:/var/lib/postgresql/data
    ports:
      - 5432:5432
  web:
    build: .
    ports:
    - 9000:9000
    volumes:
    - ~/.ivy2:/root/.ivy2
    - ~/.sbt:/root/.sbt
    links:
    - postgres
    environment: 
      - POSTGRES_SERVICE_HOST=postgres